/**
 * Export Routes — /api/export
 *
 * Provides the ZIP export endpoint which bundles generated prototype code
 * files into a downloadable archive. This is a new original feature not
 * present in the base prototype — it gives users a clean artifact they can
 * open directly in a browser without needing the Proto-Gen platform.
 */

import express from 'express';
import archiver from 'archiver';
import Session from '../models/Session.js';
import { AppError } from '../errors/AppError.js';

const router = express.Router();

/**
 * POST /api/export/zip
 *
 * Accepts a sessionId, retrieves the generated code files from MongoDB,
 * and streams a .zip archive directly to the client response.
 *
 * The archive includes:
 *   - All generated code files (index.html, app.js, etc.)
 *   - A README.txt explaining how to open the prototype
 *
 * We stream directly to res rather than buffering in memory so large
 * prototypes don't cause OOM issues on the server.
 */
router.post('/zip', async (req, res, next) => {
  try {
    const { sessionId } = req.body;

    if (!sessionId) {
      throw AppError.badRequest('A sessionId is required to export a prototype.');
    }

    // Retrieve the session and extract the generated files from the last output.
    const session = await Session.findOne({ sessionId }).lean();
    if (!session) {
      throw AppError.notFound('Prototype session');
    }

    const generatedFiles =
      session.lastOutput?.files ||
      session.lastOutput?.metadata?.files ||
      [];

    if (generatedFiles.length === 0) {
      throw AppError.badRequest(
        'This session has no generated code files to export. Generate a "Workflow + Code" prototype first.',
        'no_files_to_export'
      );
    }

    const prototypeName = (session.title || 'proto-gen-export')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const archiveFilename = `${prototypeName}.zip`;

    // Set response headers to trigger a file download in the browser.
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${archiveFilename}"`);

    // Create the archiver and pipe it directly into the response stream.
    const archive = archiver('zip', {
      zlib: { level: 6 }, // Balanced compression — not too slow, not too large.
    });

    archive.on('error', (err) => {
      console.error('[ExportRoute] Archive error:', err.message);
      // Only call next if headers haven't been sent yet.
      if (!res.headersSent) {
        next(new AppError('Failed to create export archive.', 500, 'archive_error'));
      }
    });

    archive.pipe(res);

    // Append each generated file into the archive.
    for (const file of generatedFiles) {
      const fileName = file.name || file.filename || 'file.txt';
      const fileContent = file.content || '';
      archive.append(fileContent, { name: fileName });
    }

    // Add a helpful README explaining how to use the exported prototype.
    const readmeContent = makeReadme(session.title, generatedFiles);
    archive.append(readmeContent, { name: 'README.txt' });

    await archive.finalize();

  } catch (error) {
    next(error);
  }
});

function makeReadme(title, files) {
  const fileList = files.map((f) => `  - ${f.name || f.filename}`).join('\n');
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  return [
    `Proto-Gen Exported Prototype`,
    `============================`,
    `Title: ${title || 'Untitled Prototype'}`,
    `Exported at: ${timestamp}`,
    ``,
    `Files included:`,
    fileList,
    ``,
    `How to open:`,
    `  1. Extract this ZIP to a folder.`,
    `  2. Open "index.html" in any modern web browser (Chrome, Firefox, Edge).`,
    `  3. No build step or server required — runs entirely in the browser.`,
    ``,
    `Generated by Proto-Gen — AI Prototype Generator`,
  ].join('\n');
}

export default router;
